"""empty message

Revision ID: 1c8ce43b9556
Revises: cba5f25c7db1
Create Date: 2025-09-26 19:13:47.662027

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1c8ce43b9556'
down_revision: Union[str, Sequence[str], None] = 'cba5f25c7db1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_familiars_player_id'), 'familiars', ['player_id'], unique=False)
    op.create_index(op.f('ix_inventory_items_player_id'), 'inventory_items', ['player_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_inventory_items_player_id'), table_name='inventory_items')
    op.drop_index(op.f('ix_familiars_player_id'), table_name='familiars')
    # ### end Alembic commands ###
