"""empty message

Revision ID: 9b600c1905d3
Revises: 1c8ce43b9556
Create Date: 2025-09-26 20:05:03.694640

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9b600c1905d3'
down_revision: Union[str, Sequence[str], None] = '1c8ce43b9556'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    if op.get_bind().dialect.name == 'sqlite':
        with op.batch_alter_table('inventory_items', schema=None) as batch_op:
            batch_op.create_unique_constraint('uq_inventory_player_item', ['player_id', 'item_name'])
    else:
        op.create_unique_constraint('uq_inventory_player_item', 'inventory_items', ['player_id', 'item_name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    if op.get_bind().dialect.name == 'sqlite':
        with op.batch_alter_table('inventory_items', schema=None) as batch_op:
            batch_op.drop_constraint('uq_inventory_player_item', type_='unique')
    else:
        op.drop_constraint('uq_inventory_player_item', 'inventory_items', type_='unique')
    # ### end Alembic commands ###
