services:
  bot:
    build:
      context: ./bot
      dockerfile: dockerfile
    depends_on:
      - api
    environment:
      - DISCORD_TOKEN=${DISCORD_TOKEN}
      - OWNER=${OWNER}
      - PRODUCTION=False
      - API_BASE_URL=http://api:8123
  api:
    build:
      context: ./api
      dockerfile: dockerfile
    ports:
      - "8123:8123"